### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by jbaessens** [bibigone/AstraDotNetDemo#1]
Hi, 

Thanks for your work, I search for a sample in c# and it's perfect! 
I create my own soft to manage two cameras. But I can't do body tracking on two cameras simultaneously. BodyFrame juste drop ! Does it works for you? 
I tried with your sample and it doesn't work. Also I just see one coulour source when I display the two sensors.

Thanks in advance!
Julien

**Comment by bibigone** [comment]
Hello @jbaessens,

> But I can't do body tracking on two cameras simultaneously.
> BodyFrame juste drop ! Does it works for you?

I have exactly the same issue. And definitely this is a bug (or limitation) inside Astra SDK (Body Tracking pluging). In a few days version 2.0.8 of SDK should be published. May be this new version will have appropriate fix.

> Also I just see one coulour source when I display the two sensors.

I think, that you use Astra **PRO** sensors. I also use this model. The thing is that, Astra PRO has UVC camera module for color stream and UVC webcameras are not supported by OpenNI infrastructure. This why you will not see any color in OpenCV examples with these sensors. In version 2.0.x of Astra SDK they added support of UVC web cameras. But this support is actually very buggy. Turning on of color stream results in low FPS (around 26-27 frames per seconds while without color stream it is about 29.7) and it doesn't work with two sensors. As a workaround, you can read color stream via DirectShow infrastructure and it works. But it is hard to find correspondence between web-cam devices in DirectShow and depth sensor devices in Astra SDK because in Astra SDK there is not API to get USB connection string for depth sensor :(

**Comment by jbaessens** [comment]
Thanks for this! Much hope in 2.08 so ;-)

**Comment by bibigone** [comment]
Hello @jbaessens,

I switched to 2.0.9. Now body tracking works better in case of multiple sensors. But there is flickering of body information (it become unavailable frame after frame).

Also, I described other known issues in `readme.md`.
